/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MediaFlimstrip: typeof import('./src/components/MediaFlimstrip.vue')['default']
    NumericInput: typeof import('./src/components/NumericInput.vue')['default']
    OverlaySidePanel: typeof import('./src/components/Overlay/OverlaySidePanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}